version: '3'
volumes:
    sqldb:

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        volumes:
            -   sqldb:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=accountdb
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=password
        network_mode: host
        ports:
            - "3306:3306"

    healthtrackerserver:
        container_name: healthtrackerserver
        image: healthtrackerserver:latest
        depends_on:
            - mysql
        network_mode: host
        ports:
            - "8080:8080"
